# Generated by Django 5.0.2 on 2024-02-26 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRN', models.CharField(max_length=20, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('PlanName', models.CharField(max_length=20, null=True)),
                ('ASC', models.CharField(choices=[(None, None), ('Very Low', 'Very Low'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default=None, max_length=200)),
                ('Technique', models.CharField(choices=[('VMAT', 'VMAT'), ('3D', '3D'), ('2D', '2D'), ('electron', 'electron'), ('IMRT', 'IMRT')], default='VMAT', max_length=200)),
                ('Energy', models.CharField(choices=[('6MV', '6MV'), ('16MV', '16MV'), ('6fff', '6fff'), ('10fff', '10fff'), ('6MeV', '6MeV'), ('9MeV', '9MeV'), ('12MeV', '12MeV'), ('16MeV', '16MeV'), ('6/16MV', '6/16MV')], default='6MV', max_length=200)),
                ('Dose', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('FieldStart', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('FieldStop', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('ClearCheck', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Complexity', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('MU', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('PD_Gamma', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('BeamOnTime', models.CharField(max_length=20, null=True)),
                ('TxSite', models.CharField(choices=[(None, None), ('HH', 'HH'), ('WB', 'WB'), ('GR', 'GR'), ('SC', 'SC')], default=None, max_length=200)),
                ('QAShot', models.CharField(choices=[(None, None), ('HH', 'HH'), ('WB', 'WB'), ('GR', 'GR'), ('SC', 'SC')], default=None, max_length=200)),
                ('Note', models.CharField(max_length=200, null=True)),
                ('OblFactor', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
