# Generated by Django 5.0.2 on 2024-02-28 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioTh_Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='ASC',
            field=models.CharField(blank=True, choices=[(None, None), ('Very Low', 'Very Low'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='BeamOnTime',
            field=models.FloatField(blank=True, default=-1.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='ClearCheck',
            field=models.FloatField(blank=True, default=-1.0, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Complexity',
            field=models.FloatField(default=-1.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Dose',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Energy',
            field=models.CharField(blank=True, choices=[('6MV', '6MV'), ('16MV', '16MV'), ('6fff', '6fff'), ('10fff', '10fff'), ('6MeV', '6MeV'), ('9MeV', '9MeV'), ('12MeV', '12MeV'), ('16MeV', '16MeV'), ('6/16MV', '6/16MV')], default='6MV', max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='FieldStart',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='FieldStop',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='MRN',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='MU',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Note',
            field=models.CharField(blank=True, default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='OblFactor',
            field=models.CharField(blank=True, default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='PD_Gamma',
            field=models.FloatField(blank=True, default=-1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='PlanName',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='QAShot',
            field=models.CharField(blank=True, choices=[(None, None), ('HH', 'HH'), ('WB', 'WB'), ('GR', 'GR'), ('SC', 'SC')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='TxSite',
            field=models.CharField(blank=True, choices=[(None, None), ('HH', 'HH'), ('WB', 'WB'), ('GR', 'GR'), ('SC', 'SC')], default=None, max_length=200),
        ),
    ]
